### ISSUE TITLE
Add an icon to the title page

### ISSUE THREAD

**Issue by das-jishu** [SanskritiKushik5/Payment-Gateway-Integration#4]
Hi! I would like to add an icon to the webpage to increase functionality. 😄

**Comment by SanskritiKushik5** [comment]
Sorry but this project isn't open for Hacktoberfest :)

**Comment by das-jishu** [comment]
Oh, no issues! You can still merge the pull request if you feel it would help. Thanks! 😃

**Comment by SanskritiKushik5** [comment]
Sure!
